name: Main
on:
  push:
    branches:
      - main
  schedule:
     - cron:  '8 * * * *'    # At every 15th minute
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
